# Create schema / Drop schema
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema books")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop schema books")


# function bulk_insert
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    genre = op.create_table('genre',
                            sa.Column('genre_id', sa.Integer(), sa.Identity(always=True), nullable=False),
                            sa.Column('name_genre', sa.String(), nullable=False),
                            sa.PrimaryKeyConstraint('genre_id')
                            )

    op.bulk_insert(
        genre,
        [{'name_genre': 'Фантастика'}, {'name_genre': 'Детективы'}]
    )

