"""cre tbl buy_step in books

Revision ID: 0b62edfe1d39
Revises: bd9246bd58d0
Create Date: 2024-11-13 10:31:19.534537

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b62edfe1d39'
down_revision: Union[str, None] = 'bd9246bd58d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    buy_step = op.create_table('buy_step',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('date_step_beg', sa.DATE(), nullable=True),
    sa.Column('date_step_end', sa.DATE(), nullable=True),
    sa.Column('user_created', sa.Integer(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_modified', sa.Integer(), nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('row_version', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(('buy_id',), ['books.buy.id'], ),
    sa.ForeignKeyConstraint(('step_id',), ['books.step.id'], ),
    schema='books'
    )

    op.bulk_insert(
        buy_step,
        [
            {'buy_id': 1,
             'step_id': 1,
             'date_step_beg': '2020-02-20',
             'date_step_end': '2020-02-20',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 1,
             'step_id': 2,
             'date_step_beg': '2020-02-20',
             'date_step_end': '2020-02-21',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 1,
             'step_id': 3,
             'date_step_beg': '2020-02-22',
             'date_step_end': '2020-03-07',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 1,
             'step_id': 4,
             'date_step_beg': '2020-03-08',
             'date_step_end': '2020-03-08',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 2,
             'step_id': 1,
             'date_step_beg': '2020-02-28',
             'date_step_end': '2020-02-28',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 2,
             'step_id': 2,
             'date_step_beg': '2020-02-29',
             'date_step_end': '2020-03-01',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 2,
             'step_id': 3,
             'date_step_beg': '2020-03-02',
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 2,
             'step_id': 4,
             'date_step_beg': None,
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 3,
             'step_id': 1,
             'date_step_beg': '2020-03-05',
             'date_step_end': '2020-03-05',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 3,
             'step_id': 2,
             'date_step_beg': '2020-03-05',
             'date_step_end': '2020-03-06',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 3,
             'step_id': 3,
             'date_step_beg': '2020-03-06',
             'date_step_end': '2020-03-10',
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 3,
             'step_id': 4,
             'date_step_beg': '2020-03-11',
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 4,
             'step_id': 1,
             'date_step_beg': '2020-03-20',
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 4,
             'step_id': 2,
             'date_step_beg': None,
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 4,
             'step_id': 3,
             'date_step_beg': None,
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0},
            {'buy_id': 4,
             'step_id': 4,
             'date_step_beg': None,
             'date_step_end': None,
             'user_created': 0,
             'date_created': datetime.now(timezone.utc),
             'user_modified': None,
             'date_modified': None,
             'row_version': 0}
            ]
    )


def downgrade() -> None:
    op.drop_table('buy_step', schema='books')
