"""db creation

Revision ID: 4adc220eddd8
Revises: 
Create Date: 2024-10-24 21:55:43.407313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4adc220eddd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema books")  # ADDED MANUALLY!
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name_genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    schema='books'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre', schema='books')
    op.execute("drop schema books")  # ADDED MANUALLY!
    # ### end Alembic commands ###
